#根据https://hub.docker.com/_/elasticsearch的说明，让es运行在开发模式下使用如下命令
#$ docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:tag
#  9200 is for REST.
#  9300 for nodes communication
#将docker命令得出的yaml文件应该如下
apiVersion: v1
kind: Service
metadata:
  name: es-service
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30092
  selector:
    app: es
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - image: elasticsearch:6.7.2
          name: elasticsearch
          env:
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: es-persistent-storage
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-persistent-storage
          persistentVolumeClaim:
            claimName: es-pvc
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi