apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  type: NodePort
  ports:
    - port: 5601
      nodePort: 30056
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: kibana:6.7.2
          name: kibana
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://10.42.0.101:30092