apiVersion: v1
kind: Pod
metadata:
  annotations:
    buildUrl: http://myjenkins:8080/job/pipeline1/21/
  creationTimestamp: "2019-05-27T05:35:00Z"
  labels:
    jenkins: slave
    jenkins/mypod-fbf7aad1-3282-4032-86af-974bd7955cdf: "true"
  name: mypod-fbf7aad1-3282-4032-86af-974bd7955cdf-xwxx4-gc7ps
  namespace: default
  resourceVersion: "925879"
  selfLink: /api/v1/namespaces/default/pods/mypod-fbf7aad1-3282-4032-86af-974bd7955cdf-xwxx4-gc7ps
  uid: 2b691167-8041-11e9-8919-525400261060
spec:
  containers:
    - command:
        - bash
      image: maven:3.6.1-jdk-8
      imagePullPolicy: IfNotPresent
      name: maven
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
      volumeMounts:
        - mountPath: /root/.m2
          name: maven-repo
        - mountPath: /home/jenkins
          name: workspace-volume
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-5p2b4
          readOnly: true
    - env:
        - name: JENKINS_SECRET
          value: 89f0c1245dcef5eea599ab6244ffa8e00792c2c6f063df56af8ac8f73cbb8408
        - name: JENKINS_TUNNEL
          value: myjenkins-agent:50000
        - name: JENKINS_AGENT_NAME
          value: mypod-fbf7aad1-3282-4032-86af-974bd7955cdf-xwxx4-gc7ps
        - name: JENKINS_NAME
          value: mypod-fbf7aad1-3282-4032-86af-974bd7955cdf-xwxx4-gc7ps
        - name: JENKINS_URL
          value: http://myjenkins:8080/
        - name: HOME
          value: /home/jenkins
      image: jenkins/jnlp-slave:alpine
      imagePullPolicy: IfNotPresent
      name: jnlp
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-5p2b4
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kworker1.example.com
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: maven-repo-pvc
    - emptyDir: {}
      name: workspace-volume
    - name: default-token-5p2b4
      secret:
        defaultMode: 420
        secretName: default-token-5p2b4
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2019-05-27T05:35:00Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2019-05-27T05:35:47Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2019-05-27T05:35:47Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2019-05-27T05:35:00Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://a852a1794d86f1698a337b4a265d0d40c3af26d4f0546aca7d1b8b499a092e78
      image: jenkins/jnlp-slave:alpine
      imageID: docker-pullable://jenkins/jnlp-slave@sha256:3c4227433a1bbd070b250d491bdee1696e6c163cff8a470df9c848da94306693
      lastState: {}
      name: jnlp
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: "2019-05-27T05:35:47Z"
    - containerID: docker://68c195db5f7688e71117590e6157009d1c1d198b5329714f7cecdd26ad774739
      image: maven:3.6.1-jdk-8
      imageID: docker-pullable://maven@sha256:0c91b81f50eea08a67111d1a9b97492c37995de22b230c1f02203b7f5f7fef58
      lastState: {}
      name: maven
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: "2019-05-27T05:35:46Z"
  hostIP: 192.168.50.101
  phase: Running
  podIP: 10.244.1.161
  qosClass: BestEffort
  startTime: "2019-05-27T05:35:00Z"
