apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-repo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.110
    path: "/srv/nfs/kubedata/maven/repo"
