apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
spec:
  volumes:
    - name: kube-config
      configMap:
        name: kube-config-map
        items:
          - key: config
            path: config
  containers:
    - name: kubectl
      image: roffe/kubectl
      tty: true
      volumeMounts:
        - name: kube-config
          mountPath: /root/.kube
