apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.50.110
    path: "/srv/nfs/kubedata/nexus"
